Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerUpdateInput, TrainerUncheckedUpdateInput> & TrainerUncheckedUpdateInput) | (Without<...> & TrainerUpdateInput)'.
20     update: {isActive: true},
                ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3393:5
    3393     update: XOR<TrainerUpdateInput, TrainerUncheckedUpdateInput>
             ~~~~~~
    The expected type comes from property 'update' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:31:7 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerCreateInput, TrainerUncheckedCreateInput> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput)'.

31       isActive: true,
         ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3389:5
    3389     create: XOR<TrainerCreateInput, TrainerUncheckedCreateInput>
             ~~~~~~
    The expected type comes from property 'create' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:41:14 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerUpdateInput, TrainerUncheckedUpdateInput> & TrainerUncheckedUpdateInput) | (Without<...> & TrainerUpdateInput)'.

41     update: {isActive: true},
                ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3393:5
    3393     update: XOR<TrainerUpdateInput, TrainerUncheckedUpdateInput>
             ~~~~~~
    The expected type comes from property 'update' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:52:7 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerCreateInput, TrainerUncheckedCreateInput> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput)'.

52       isActive: true,
         ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3389:5
    3389     create: XOR<TrainerCreateInput, TrainerUncheckedCreateInput>
             ~~~~~~
    The expected type comes from property 'create' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:62:14 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerUpdateInput, TrainerUncheckedUpdateInput> & TrainerUncheckedUpdateInput) | (Without<...> & TrainerUpdateInput)'.

62     update: {isActive: true},
                ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3393:5
    3393     update: XOR<TrainerUpdateInput, TrainerUncheckedUpdateInput>
             ~~~~~~
    The expected type comes from property 'update' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:73:7 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerCreateInput, TrainerUncheckedCreateInput> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput)'.

73       isActive: true,
         ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3389:5
    3389     create: XOR<TrainerCreateInput, TrainerUncheckedCreateInput>
             ~~~~~~
    The expected type comes from property 'create' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:84:14 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerUpdateInput, TrainerUncheckedUpdateInput> & TrainerUncheckedUpdateInput) | (Without<...> & TrainerUpdateInput)'.

84     update: {isActive: true},
                ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3393:5
    3393     update: XOR<TrainerUpdateInput, TrainerUncheckedUpdateInput>
             ~~~~~~
    The expected type comes from property 'update' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:95:7 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<TrainerCreateInput, TrainerUncheckedCreateInput> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput)'.

95       isActive: true,
         ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:3389:5
    3389     create: XOR<TrainerCreateInput, TrainerUncheckedCreateInput>
             ~~~~~~
    The expected type comes from property 'create' which is declared here on type '{ select?: TrainerSelect<DefaultArgs> | null | undefined; include?: TrainerInclude<DefaultArgs> | null | undefined; where: TrainerWhereUniqueInput; create: (Without<...> & TrainerUncheckedCreateInput) | (Without<...> & TrainerCreateInput); update: (Without<...> & TrainerUncheckedUpdateInput) | (Without<...> & Traine...'
prisma/seed.ts:105:16 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<UserUpdateInput, UserUncheckedUpdateInput> & UserUncheckedUpdateInput) | (Without<...> & UserUpdateInput)'.

105       update: {isActive: true},
                   ~~~~~~~~

  node_modules/.prisma/client/index.d.ts:2309:5
    2309     update: XOR<UserUpdateInput, UserUncheckedUpdateInput>
             ~~~~~~
    The expected type comes from property 'update' which is declared here on type '{ select?: UserSelect<DefaultArgs> | null | undefined; include?: UserInclude<DefaultArgs> | null | undefined; where: UserWhereUniqueInput; create: (Without<...> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput); update: (Without<...> & UserUncheckedUpdateInput) | (Without<...> & UserUpdateInput); }'
prisma/seed.ts:113:11 - error TS2353: Object literal may only specify known properties, and 'isActive' does not exist in type '(Without<UserCreateInput, UserUncheckedCreateInput> & UserUncheckedCreateInput) | (Without<...> & UserCreateInput)'.

113           isActive: true,
              ~~~~~~~~