error TS2339: Property 'booking' does not exist on type 'PrismaClient<PrismaClientOptions, never, DefaultArgs>'.
221       await prisma.booking.upsert({